---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - python-pip
    - python-psycopg2
    - git
    - binutils
    - libproj-dev
    - gdal-bin

- name: Clone Django Repository
  git: repo=https://github.com/ndraper2/django-imager.git dest={{ home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get DB Password
  include_vars: secrets.yml


- name: Set DB URL
  set_fact:
    db_url: "postgis://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: imagersite.production
    command: migrate

- shell: psql postgres://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }} -c "UPDATE django_site set domain = '{{ ec2_public_dns_name }}' WHERE id = 1;"
- shell: psql postgres://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }} -c "UPDATE django_site set name = 'django imager' WHERE id = 1;"

- name: Collect Static Files
  environment:
    DATABASE_URL: "{{ db_url }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: imagersite.production
    command: collectstatic
